  version: "3.9"

  services:
    # Main Nginx reverse proxy
    nginx-proxy:
      image: jwilder/nginx-proxy:alpine
      container_name: nginx-proxy
      restart: unless-stopped
      ports:
        - "80:80"
        - "443:443"
      networks:
        - proxy-net
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
        - nginx_certs:/etc/nginx/certs:rw
        - nginx_vhost:/etc/nginx/vhost.d:rw
        - nginx_html:/usr/share/nginx/html:rw
      extra_hosts:
        - "host.docker.internal:host-gateway"

    # Let's Encrypt companion for automatic SSL
    nginx-proxy-acme:
      image: jrcs/letsencrypt-nginx-proxy-companion
      container_name: nginx-proxy-acme
      restart: unless-stopped
      depends_on:
        - nginx-proxy
      networks:
        - proxy-net
      environment:
        - NGINX_PROXY_CONTAINER=nginx-proxy
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - nginx_certs:/etc/nginx/certs:rw
        - nginx_vhost:/etc/nginx/vhost.d:rw
        - nginx_html:/usr/share/nginx/html:rw

    # Backend proxy for your Node/PM2 backend
    pm2-backend-proxy:
      image: nginx:alpine
      container_name: pm2-backend-proxy
      restart: unless-stopped
      networks:
        - proxy-net
      volumes:
        - /home/iomd/backend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      environment:
        - VIRTUAL_HOST=ap.emessmodasa.site
        - LETSENCRYPT_HOST=ap.emessmodasa.site
        - LETSENCRYPT_EMAIL=harshprajapati8583@gmail.com
      extra_hosts:
        - "host.docker.internal:host-gateway"
      depends_on:
        - nginx-proxy

    # Frontend app
    default-frontend:
      build:
        context: /home/iomd/frontend
        dockerfile: Dockerfile
      container_name: default-frontend
      restart: unless-stopped
      networks:
        - proxy-net
      environment:
        - VIRTUAL_HOST=app.emessmodasa.site
        - LETSENCRYPT_HOST=app.emessmodasa.site
        - LETSENCRYPT_EMAIL=harshprajapati8583@email.com
      volumes:
        - /home/iomd/frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      depends_on:
        - nginx-proxy


  volumes:
    nginx_certs:
    nginx_vhost:
    nginx_html:

  networks:
    proxy-net:
      external: true
