version: '3'

services:
  server:
    build: .
    container_name: backend-server
    ports:
      - "5000:5000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /var/run/docker.sock:/var/run/docker.sock  # 👈 Mount docker.sock
    networks:
      - deploy-net

  nginx-proxy:
    image: nginx:alpine
    container_name: nginx_proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"  # Changed to avoid port conflict
    networks:
      - deploy-net

networks:
  deploy-net:
    driver: bridge
